### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by javiermortiz** [RoodeAwakening/sirHiss_Crypto#1]
Hi Derek! here are some comments about your docs:

MVP list
- [x] Right now you are separating Dashboard, Portfolio, Transactions but in reality their are the same and most important feature. You want to have a balance and a chart. The balance consist of cash and share values. The balance should reflect the rise and fall of the shares values + cash available. You will need an api to grab historical/live data of the stock market.
- [x] Assets looks good. It completes the Transactions functionality.
- [x] Watchlist looks good, add it as one of your MVPs now that you are merging Dashboard/Portfolio/Transactions.
- [x] Search looks good, add it as one of your MVPs now that you are merging Dashboard/Portfolio/Transactions.

Db Schema
- [x] Add it to your wiki, and add the constraints you plan to apply to columns.
- [x] The portfolio holdings should belong to a user. The way I'd implement this table is to add a column for cash, a current balance and a starting balance so that you can show how the balance has changed based on the historical values of your stocks.
- [x] The transaction needs to be join to the assets table to allow a user to own an asset and to keep track how many shares of an asset a user owns.

I think I might be missing context for some of the schema decisions. Let's chat about it in person. Please reach out via dm if we haven't chat about it before 11am PST.

**Comment by RoodeAwakening** [comment]
- Combined Dashboard, Portfolio, Transaction under one MVP  (D-P-T).
-  Listed the top two API's I am looking at for the market data.
-  Added an API for news.

**Comment by RoodeAwakening** [comment]
Watchlist (DB) - look at removing the listAssets table and having everything under a single watchlist as there will not be different types of lists?? or maybe there will be.. thoughts...??
